version: '3'
services:
  leafy-postgresql:
    image: sungjunlee2000/leafy-postgresql:latest
    volumes:
      - mydata:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # 외부에서 접근하려면 포트를 매핑합니다.
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
    restart: always

  leafy-backend:
    build: ./leafy-backend
    image: leafy-backend:5.0.0-compose
    environment:
      - DB_URL=postgres://myuser:mypassword@leafy-postgresql:5432/mydb
    depends_on:
      - leafy-postgresql
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 512M
    restart: on-failure

  leafy-front:
    build: ./leafy-frontend
    image: sungjunlee2000/leafy-frontend:latest
    environment:
      - BACKEND_HOST=leafy-backend
    ports:
      - "80:80"
    depends_on:
      - leafy-backend
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 64M
    restart: on-failure

volumes:
  mydata: